services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3306:3306'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: verysecret
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
