services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - '3306:3306'
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: verysecret
    depends_on:
      - mysql
    networks:
      - app-network
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566" # Main LocalStack Gateway
      - "4571:4571" # S3 Endpoint
    environment:
      - SERVICES=s3 # Specify services you want to use, e.g., s3, dynamodb, lambda, etc.
      - DEBUG=1 # Enable debugging
      - AWS_ACCESS_KEY_ID=test # Default Access Key for local AWS
      - AWS_SECRET_ACCESS_KEY=test # Default Secret Key for local AWS
      - DATA_DIR=/tmp/localstack/data # Persistent data directory
    volumes:
      - "./localstack:/tmp/localstack" # Bind a local directory for persistence
#      - "./localstack-data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock" # Allow Docker Lambda executions
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
